---
apiVersion: v1
kind: Pod
metadata:
  name: client2-java-otel-k8s
spec:
  containers:
  - name: client2-java-otel-k8s
    image: quay.io/vvydier123/splk-java
    env:
    - name: SPLUNK_OTEL_AGENT
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: service.name=client2-java-otel-k8s,deployment.environment=<ENV PREFIX>-apm-workshop
    - name: SPLUNK_METRICS_ENABLED
      value: "true"
    - name: SPLUNK_METRICS_ENDPOINT
      value: http://$(SPLUNK_OTEL_AGENT):9943
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://$(SPLUNK_OTEL_AGENT):4317
    command: ["/bin/sh"]
    args: ["run-client.sh"]
