---
### Dotnet Requests Pod
apiVersion: v1
kind: Pod
metadata:
  name: client-dotnet6-k8s
spec:
  containers:
  - name: client-dotnet6-k8s
    image: quay.io/vvydier123/splk-dotnet6
    env:
    - name: SPLUNK_OTEL_AGENT
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: SIGNALFX_ENDPOINT_URL
      value: "http://$(SPLUNK_OTEL_AGENT):9411/api/v2/spans"
    - name: SIGNALFX_SERVICE_NAME
      value: dotnet5-httpget
    - name: SIGNALFX_ENV
      value: <ENV PREFIX>-apm-workshop
    - name: CORECLR_ENABLE_PROFILING
      value: "1"
    - name: CORECLR_PROFILER
      value: '{B4C89B0F-9908-4F73-9F59-0D77C5A06874}'
    - name: CORECLR_PROFILER_PATH
      value: /opt/signalfx-dotnet-tracing/SignalFx.Tracing.ClrProfiler.Native.so
    - name: SIGNALFX_DOTNET_TRACER_HOME
      value: /opt/signalfx-dotnet-tracing
    command: ["/bin/sh"]
    args: ["/App/run-client.sh"]
