apiVersion: v1
kind: Pod
metadata:
  name: java-manual-inst-k8s
spec:
  containers:
  - name: java-manual-inst-k8s
    image: 'vvydier123.io/vvydier123/splk-java:latest'
    ports:
      - name: http
        containerPort: 3000
    env:
    - name: SPLUNK_OTEL_AGENT
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: service.name=manualinst-java-otel-k8s
    - name: SPLUNK_METRICS_ENDPOINT
      value: http://$(SPLUNK_OTEL_AGENT):9943
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://$(SPLUNK_OTEL_AGENT):4317
    command: ["/bin/sh"]
    args: ["./manual-inst/run-java-manual-inst-k8s.sh"]
