apiVersion: v1
kind: Pod
metadata:
  name: py-autogen
spec:
  containers:
  - name: py-autogen
    image: quay.io/vvydier123/splk-python-autogen
    ports:
    - containerPort: 6379
    env:
    - name: TZ
      value: America/New_York
    - name: REDISHOST
      value: redis
    - name: SPLUNK_OTEL_AGENT
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: deployment.environment=otel-demo
    - name: OTEL_SERVICE_NAME
      value: python-autogen-otel
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://$(SPLUNK_OTEL_AGENT):4317
    command: ["/bin/sh"]
    args: ["run-autogen-ext.sh"]
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: quay.io/vvydier123/redis
        ports:
        - containerPort: 6379
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
