FROM openjdk:8-slim
RUN apt-get update && \
    apt-get -y install curl && \
    mkdir /home/code
WORKDIR /home/code
COPY . /home/code/
RUN ["chmod", "+x", "./manual-inst/run-java-manual-inst-k8s.sh"]
ENTRYPOINT /bin/sh ./manual-inst/run-java-manual-inst-k8s.sh